<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ElroukenAljamil.Common\ElroukenAljamil.Common.csproj" />
    <ProjectReference Include="..\ElroukenAljamil.EventBus\ElroukenAljamil.EventBus.csproj" />
    <ProjectReference Include="..\ElroukenAljamil.Search.Domain\ElroukenAljamil.Search.Domain.csproj" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="MediatR" Version="12.2.*" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.*" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.*" />
	</ItemGroup>
</Project>
